CREATE TABLE IF NOT EXISTS artworks (
 id INT,
 title VARCHAR(100),
 created VARCHAR(100),
 medium VARCHAR(30),
 dimensions VARCHAR(12),
 credit INT,
 accessionnumber INT,
 classification VARCHAR(10),
 department INT,
 acquired VARCHAR(10),
 catalogued BOOLEAN,
 url VARCHAR(200),
 thumbnailurl VARCHAR(200),
 circumference int,
 depth int,
 diameter int,
 height int,
 length int,
 weight int,
 width int,
 duration int,
 PRIMARY KEY (id)
);